### PR TITLE
Move discovery server source code to discovery.etcd.io repo

### PR DESCRIPTION
**Pull request by eduartua**
For some reason the previous latest version v3.3.17 didn't have some packages required by the discovery server itself (e.g. go.etcd.io/etcd/etcdserver/api/v2store) so go modules and vendoring failed. Now this is pinned to the specific etcd module v3.4.3 (latest release). The server was tested with a single member etcd server, then creating a multi-member etcd server using the `hack/insta-discovery/discovery` script and it worked good.
@philips Please, let us know what you do think about this to continue with the cloud build process.

### CODE REVIEW

**Comment by philips** [comment]
lgtm

**Comment by victortrac** [comment]
@philips I spoke with @idvoretskyi about this over the weekend, and we both think it may be better to put the go code for discoveryserver into its own repo, leaving the infra/meta stuff in this repo. 

I don't have access to do this. Can you make a new `discoveryserver` repo and add me and @eduartua as a writer?  I'll work with @eduartua to commit this code there.

**Comment by philips** [comment]
Done.

**Comment by eduartua** [comment]
Closing this PR. Discovery Server source code will live in its own [repo](https://github.com/etcd-io/discoveryserver).

**Pull request closed without merging**
